AWSTemplateFormatVersion: "2010-09-09"
Description: GIT Repo for Fargate Application
Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Join [ '', [ !Ref 'AWS::StackName', 'Repository' ] ]
Outputs:
  CodeCommitRepositoryName:
    Value: !GetAtt CodeCommitRepository.Name
  CodeCommitRepositoryARN:
    Value: !GetAtt CodeCommitRepository.Arn
  CodeCommitRepositoryCloneURL:
    Value: !GetAtt CodeCommitRepository.CloneUrlSsh
